server:
  port: 9000
spring:
  application:
    name: chatApp-userCenter
# 注册服务到nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#management:
#  endpoints:
#    web:
#      exposure:
#        include: *
